#configmap_hw23.yaml
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-configmap
data:
  http_port: "8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <html>
    <h1>Hello Igor!</h1>
    </html>